# Generated by Django 4.1.7 on 2023-02-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_days', models.IntegerField()),
                ('requested_date', models.DateField()),
                ('date_needed', models.DateField()),
                ('members', models.IntegerField()),
                ('doc1', models.FileField(max_length=254, upload_to=None)),
                ('doc2', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='building_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField(default=0)),
                ('house_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('capacity', models.IntegerField()),
                ('picture', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('rental', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('document', models.FileField(max_length=254, upload_to=None)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('districtname', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='contact',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='fname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='review_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('card_no', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_details')),
            ],
        ),
        migrations.AddField(
            model_name='building_details',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.owner_details'),
        ),
        migrations.AddField(
            model_name='building_details',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building_details'),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.owner_details'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_details'),
        ),
    ]
