# Generated by Django 4.1.7 on 2023-02-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_building_details_owner_details_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
