# Generated by Django 4.1.3 on 2023-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
