# Generated by Django 4.1.3 on 2023-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_details_contact_alter_user_details_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_needed',
            new_name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_days',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
