# Generated by Django 4.1.3 on 2023-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_details_contact_alter_user_details_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='place',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user_id',
        ),
        migrations.AddField(
            model_name='owner_details',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner_details',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner_details',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc1',
            field=models.FileField(upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc2',
            field=models.FileField(upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='building_details',
            name='picture',
            field=models.ImageField(upload_to='Building'),
        ),
        migrations.AlterField(
            model_name='owner_details',
            name='document',
            field=models.FileField(upload_to='ownerdocs'),
        ),
    ]
