# Generated by Django 4.1.3 on 2023-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_user_login_remove_place_p_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Not Approved', max_length=100),
        ),
    ]
