# Generated by Django 4.2.1 on 2023-05-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_owner_details_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_details',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
    ]
